FROM mcr.microsoft.com/devcontainers/javascript-node:0-18

# Install additional tools if needed
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-tool-here>